### ISSUE TITLE
Do not change user options

### ISSUE THREAD

**Issue by rosanneturner** [AlexanderLyNL/safestats#13]
Please make sure that you do not change the user's options, par or working directory. If you really have to do so within functions, please ensure with an immediate call of on.exit() that the settings are reset when the function is exited

**Comment by AlexanderLyNL** [comment]
For t-tests: I added the on.exit() everytime 

> oldPar <- setSafeStatsPlotOptionsAndReturnOldOnes()
>   on.exit(graphics::par(oldPar))
