### ISSUE TITLE
nPlan, nPlanBatch and nPlanExpected

### ISSUE THREAD

**Issue by rosanneturner** [AlexanderLyNL/safestats#42]
What we call "nPlan" now in the t- and z-test (I am not sure about the logrank test) should be called "nPlanBatch" and should be printed at the bottom of print.safeDesign, in a note.

For prospective designs, "nPlan" should be changed to be the nPlan under optional stopping (i.e., <insert desired power> quantile of M simulated stopping times under an optional stopping experiment with parameters set according to the design, with nMax set to infinity).

"nPlanExpected" should be available when requested in the design function: nPlanExpected is the mean of M simulated stopping times under optional stopping, with nMax set to nPlan defined as above.

**Comment by AlexanderLyNL** [comment]
Done
