### ISSUE TITLE
Safe test print function: add confidence intervals 

### ISSUE THREAD

**Issue by rosanneturner** [AlexanderLyNL/safestats#45]
For all tests where possible (@AlexanderLyNL logrank and z-test if I am correct?) confidence intervals should be printed by default in the print.safeTest function. For the logrank test, the z-based version can be printed for now, with a warning. If you have finalized the code for the z- and logrank printing could you warn me, then I will format the 2x2 design accordingly!

**Comment by AlexanderLyNL** [comment]
Done
